---
title: "Assignment 3: Almond Profit Function"
author: "Michael Zargari & Guillermo Romero"
date: today
execute:
  warning: false
format:
  pdf:
      toc: false
      shift-heading-level-by: 2
      fig-pos: "H"
      fig-cap-location: top
      geometry:
        - top=1in
        - right=.8in
        - bottom=1in
        - left=.8in
      link-citations: yes
      linkcolor: blue
      include-in-header:
        text: |
          \usepackage{fancyhdr}
          \usepackage{titling}
          \pagestyle{fancy}
          \fancyhf{}
          \renewcommand\maketitle{
            \fancyhead[C]{
              \thetitle
              \ifx \theauthor\empty  \else \ – \theauthor \fi
              \ifx \thedate\empty  \else \ – \thedate \ \fi
            }
          }
          \fancyfoot[C]{\thepage}
editor:
  markdown:
    wrap: sentence
---

## Loading packages

```{r setup, message=FALSE}
library(tidyverse) ## Data manipulation
library(here)      ## Easy filepaths
library(janitor)   ## Clean column names
library(flextable) ## Output findings in nice table
library(ggthemr)   ## Creating cool themes
library(patchwork) ## Combining graphs side-by-side
```

## Read in Data

```{r}
clim_df <- read_table(here("clim.txt")) %>% 
  clean_names()
```

# Source Function

```{r}
source(here('almond_profit_function.R'))
```

# Application of Function to clim.txt

```{r}
profits_per_year <- almond_profit(clim_df, almond_price = 4036, average_yield = 50)

profit_model <- tibble(
  year = unique(clim_df$wy),
  profits = profits_per_year
)
profit_model
```
# Informal Sensitivity Analysis

```{r}

ggthemr('flat dark', type ='outer', layout= 'scientific')
# Run the almond_profit function with different parameter values and collect the results

# Holding average yield to 50 Tons
parameter_values <- runif(n = 10 , min =.01, max = 0.9)
profit_results <- data.frame()

for (param in parameter_values) {
  profit <- almond_profit(clim_df, almond_price = param)
  temp_df <- data.frame(parameter = param, profit = profit)
  profit_results <- rbind(profit_results, temp_df)
}

# Use ggplot to create a boxplot of profits against the input parameters
price_diff_plot <- ggplot(profit_results, aes(x = factor(parameter), y = profit)) +
  geom_boxplot() +
  labs(x = "Almond Price ($/acre)", y = "Almond Profit ($/acre)") 
```

```{r}
# Run the almond_profit function with different parameter values and collect the results
average_yield_values <- runif(n = 10 , min = 1, max = 10)
profit_results <- data.frame()

for (avg_yield in average_yield_values) {
  profit <- almond_profit(clim_df, average_yield = avg_yield)
  temp_df <- data.frame(average_yield = avg_yield, profit = profit)
  profit_results <- rbind(profit_results, temp_df)
}

# Use ggplot to create a boxplot of profit against the input average yield values
yield_diff_plot <-ggplot(profit_results, aes(x = factor(average_yield), y = profit)) +
  geom_boxplot() +
  labs(x = "Average Yield (tons/farm)", y = "Almond Profit ($/acre)")
```
```{r}
#| echo: false
price_diff_plot 
yield_diff_plot
```

```{r}

ggplot(profit_model, aes(x = year, y = profits)) +
  geom_col()
```